sudo: false
language: node_js
cache:
  directories:
  - node_modules
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id:
    secure: JIvPWg4Yy/BnyT0bICLZVhhAeLSoZsQgE/OBlzZAojieuEKESEwqZqlqJNQ2BuTuN2w5zGn0FFvWbVIGXxI5QGKLZrgtEU+qYLAxx51fdZTxpNc3lOFDglRhzKqiDmfiE89o7Qo93QXKLFqI8rjOSoqurLEPkaSX6RImW1LDeyfftlQNT41GVA3AkMTGRfa9/lWZCIyu1vK07T5pI+OCadOCQYsYcm0ELvrpW81JHtWwK4R8oBzVwpfBaHDLPElzdKwBaAwNPLH8aCWRPSkip9dJl3Ju/rd47yCN0cX5V/bxODVQR3c/oujPgfbwjDz9Zyip4y9N16H5tr98WwOfgJfwDarMUW6ngztkVql9EMDPwYlJssnIoFIoTJtYe7B4DWoIBXgiEsUOgn7sT6VJRGCT10/n8VrBmQXy48wTKVXH/PdzGiq+VQ5cAuWCzzHCjMeR8paq/5TbN3qjPQcrVOC0zPTG0ce+vvGB5vJrhMUvcKc7tc4VrZNv6VVhjstHgmPMYCntwWyQMOwcokzbdUiRUUcxo3nEDVaIBhFybgz3z2qORmm8IE2XcZB9NPgBqDrarnstMZN2uCJk4rmuRZImJHJ3IlgUfHT2Nu8kdylTkZJkl4H22DIvkxozkPPDXgnzmlWSWNmMbeaHQnSEd58RaFeyCBGL+9iDYutQBEU=
  secret_access_key:
    secure: IcBf8u6jJiXbPk7xUHkqvRh7XxApEEojl+ULRDBtfPMxDgPv0HOxrxht+2BonzmDUbwN75DhcU4hw3tZMgI4Q9pAzOpmQD452FaFF8W2n0AxEiZ41t83vCmqHEv2rFhDOxi8abupbqLlCDcf1C2uy9QzAIKFrJytLJZjCYMiuUyUlCuxVEhVgGOkmWna7v1Jl7Jc/0qChV3V6bATFi0CeGNqakIR+RHHmuj2IqG91YBRZl882F7FzVggn5zZszJmA5vv2Nm8Y+L/k/AWJhTNYhKQKG933gLY08bKzyKRJC5k/WY0rEi01+8F29b3DATTkTCmMrP14lGoFVdDSJKFd/Pgt3PRArTMWmtsuqZ/jeipmw9FV6nVYQUVGlM3I1wKnCM3C51cZ5CRuG3XD7JptFWAxwXrEBS2VOnOvEq+LNZaN1FPhlEEQtxt0AjOK1gEkfX5Ow+QhLSIuUVx/lNZ4CnmN/PuJprFkCoK0iq+Pg9jmCKB53cqamKmv/qZhxfxBiDGooqIFQKhx2b+5AGuDge4XvfpfwUsQkTIDOkD18JEne2bUUAs3uJN3CnPtLz1GHup8QE/SKxWJQPtC2U8Qm4Yldua3HHA7QAPa1byB2I+YJWXKLbrLQp+2kPmYTbwnUYTr5gFs9F+qZomf6R6am81SzC9RhHXI3RWjvvsBSY=
  bucket: staging-bp-decommissioning
before_script:
  - npm prune
script:
  - npm run build
after_success:
  # deploy to AWS
  - npm run deploy